# see  https://argoproj.github.io/argo-workflows/walk-through/dag/
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wonderful-python
  namespace: playground
  labels:
    example: 'true'
spec:
  entrypoint: diamond
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: 1234567890.dkr.ecr.eu-central-1.amazonaws.com/python-workflow-container:master-36f12086-1663057450
        command: [ "python", "./main.py", "{{inputs.parameters.message}}"]
    - name: diamond
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters: [{name: message, value: A}]
          - name: B
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: B}]
          - name: C
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: C}]
          - name: D
            dependencies: [B, C]
            template: echo
            arguments:
              parameters: [{name: message, value: D}]
